<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.mac08-0ss-hk</groupId>
        <artifactId>mem0ai4j-parent</artifactId>
        <version>0.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <artifactId>mem0ai4j-langchain4j</artifactId>
    <name>mem0ai4j-langchain4j</name>
    <description>Mem0 Java SDK Langchain4j Integration</description>

   <dependencies>
       <dependency>
           <groupId>io.github.mac08-0ss-hk</groupId>
           <artifactId>mem0ai4j-core</artifactId>
           <version>${project.version}</version>
       </dependency>
       <dependency>
           <groupId>dev.langchain4j</groupId>
           <artifactId>langchain4j</artifactId>
       </dependency>
       <dependency>
           <groupId>org.junit.jupiter</groupId>
           <artifactId>junit-jupiter</artifactId>
           <scope>test</scope>
       </dependency>
       <dependency>
           <groupId>org.slf4j</groupId>
           <artifactId>slf4j-simple</artifactId>
       </dependency>
   </dependencies>


</project>
